x-base_rails: &base_rails
  env_file:
    - .env
  networks:
    - pomolog_network
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - bundle:/app/vendor/bundle
    # - node_modules:/app/node_modules
    # - front_modules:/app/frontend/node_modules
    # - ~/.aws:/root/.aws
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - db:/var/lib/mysql
    networks:
      - pomolog_network

  app:
    <<: *base_rails
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${BACKEND_PORT} -b '0.0.0.0'"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo

volumes:
  db:
    driver: local
  bundle: 
    driver: local
  # node_modules:
  #   driver: local
  # front_modules:
  #   driver: local

networks:
  pomolog_network:
